export const LoginActionConstants = {
  SET_AUTHENTICATED: "SET_AUTHENTICATED",
  LOGIN_REQUESTING: "LOGIN_REQUESTING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  RESET_LOGIN: "RESET_LOGIN",
};
